### ISSUE TITLE
Import Error: cannot import name 'SortedDict'

### ISSUE THREAD

**Issue by momomimachli** [feincms/feincms-elephantblog#52]
Hello,

With Django 1.9, when running the page extension, I got the following error:

    Import Error: cannot import name 'SortedDict'

This error is discussed here: https://github.com/aljosa/django-tinymce/issues/114

The solution would be to replace on line 4 of file feincms-elephantblog/elephantblog/navigation_extensions/common.py:

    from django.utils.datastructures import SortedDict

by

    from collections import OrderedDict as SortedDict

**Comment by matthiask** [comment]
Thanks! We should probably just drop compatibility with Python<2.7.
