### ISSUE TITLE
makemigrations fails with SystemCheckError

### ISSUE THREAD

**Issue by elmcrest** [feincms/feincms-elephantblog#64]
Hey, I'm playing with elephantblog and also I'm new to FeinCMS. While following the documentation I'm now stuck with this error:

```bash
(rblog) usr:~$ python manage.py makemigrations
SystemCheckError: System check identified some issues:

ERRORS:
elephantblog.MediaFileContent.mediafile: (fields.E300) Field defines a relation with model 'MediaFile', which is either not installed, or is abstract.
```

while I'm trying to solve it, any hints are appreciated :smile: 

it's a fresh project with just an app `app` added and in the models.py the content as mentioned in the documention, so:
```python
from django.utils.translation import gettext_lazy as _
from feincms.content.richtext.models import RichTextContent
from feincms.content.medialibrary.models import MediaFileContent
import feincms_cleanse

from elephantblog.models import Entry

Entry.register_extensions(
    "feincms.module.extensions.datepublisher",
    "feincms.module.extensions.translations",
    "elephantblog.extensions.blogping",
)
Entry.register_regions(("main", _("Main content area")))

Entry.create_content_type(
    RichTextContent, cleanse=feincms_cleanse.cleanse_html, regions=("main",)
)

Entry.create_content_type(MediaFileContent, TYPE_CHOICES=(("default", _("default")),))


```

**Comment by matthiask** [comment]
Did you add `feincms.module.medialibrary` to your `INSTALLED_APPS`?

**Comment by elmcrest** [comment]
ok, that probably was the issue - though to my defense it wasn't explicitely mentioned in the docs :P
granted, I could have come up with that myself, but since I was just trying and playing I guess I didn't invest enough time.
anyways, thx for the help, I'll close this issue now.

**Comment by matthiask** [comment]
I'll reopen as a documentation issue.

**Comment by elmcrest** [comment]
Nice!

Btw, is there an somehow official community chat for finecms available?
If not I‘d vote for telegram... or one of the usual suspects of course - maybe even keybase.io ;)

**Comment by matthiask** [comment]
There is the mailing list I know of:
https://groups.google.com/forum/#!forum/django-feincms

Also, there was (is?) an IRC channel on freenode at a time, but it was not
very active either.

Personally, I'm finding my email and Github habits bad enough, and quit all
work-related chat tools (Slack etc.) because I couldn't cope with my own
habits around them so I'm not sure I can endorse or healthily join one of
the tools you're mentioning :-(
