### ISSUE TITLE
outdated Documentation: No module named 'feincms_cleanse'

### ISSUE THREAD

**Issue by elmcrest** [feincms/feincms-elephantblog#65]
this issue is here to have a reminder to update the docs, or if someone might not come up with the Idea himself...

```bash
ModuleNotFoundError: No module named 'feincms_cleanse'
```
solution
```bash
pip install feincms_cleanse
```

**Comment by matthiask** [comment]
I added a reference to https://github.com/matthiask/html-sanitizer/ instead, which is actively maintained (and tested), but has its roots in feincms-cleanse.
