### ISSUE TITLE
outdated documentation: include urls

### ISSUE THREAD

**Issue by elmcrest** [feincms/feincms-elephantblog#67]
since django 2.x the urls config has a new way without the need to use regex.

while it's compatible to the old variant, for me the simplest solution to include elephantblog urls was:

```python
from django.urls import path, include
from elephantblog import urls as elephanturls

urlpatterns += [path("blog/", include(elephanturls))]
```

**Comment by matthiask** [comment]
I'd still recommend using `url()` (at least in the docs) as long as we're still supporting Django versions <2.0
