### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by elmcrest** [feincms/feincms-elephantblog#68]
after adding a bunch of new Issues, I noticed that the last issues were from 2016.
So, is this project still alive and used?

thx

**Comment by matthiask** [comment]
Hi,

Yes, it's still being used, but mostly in maintenance mode. 

We're using https://feincms3.readthedocs.io/ and https://django-content-editor.readthedocs.io/ for new sites these days.

**Comment by mjl** [comment]
As an aside, I still use Feincms 1.x and plan to keep it alive as long as possible, as I have a lot of vested interest (aka lots of content types, and lots of sites running on it, and no budget to migrate "just because"). I haven't explored moving to feincms3 yet, as we are rather happy with the 1.x status.

        mjl

**Comment by matthiask** [comment]
I should add that the "maintenance mode" comment above mostly concerns elephantblog, and not FeinCMS 1.x (which I am also planning to keep alive)

**Comment by elmcrest** [comment]
Alright, thx for the info about feincms3 and django-content-editor. Maybe you want to add hints to the feincms docs since that was my way of eventually lading here. 
Anyways, cool, I probably don‘t have to implement my own blog with django :)

**Comment by elmcrest** [comment]
I guess that should be enough information for anyone interested, could be opened of course in the future in case it's needed. thx for the answers matthiask and mjl.

**Comment by matthiask** [comment]
Btw, I'm starting a series of posts motivated by this exchange: https://406.ch/writing/the-future-of-feincms/
